branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - "1.0"
  - "1.2"
  - "1.3"
  - nightly

matrix:
  fast_finish: true

notifications:
    email: false

script:
  - julia --check-bounds=yes etc/travis-test.jl
  - julia --check-bounds=yes etc/travis-coverage.jl
