language: julia
os:
  - linux
  - osx
  - windows
julia:
  - "1.0"
  - "1.1"
  - "1.2"
  - "1.3"
  - "nightly"

notifications:
    email: false

script:
  - julia --check-bounds=yes etc/travis-test.jl
