name = "CoverageTools"
uuid = "5c0200ba-f6cc-4d9c-a80b-82aea8bba5d6"
authors = ["Iain Dunning <iaindunning@gmail.com>"]
version = "1.0.0"

[deps]
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"

[compat]
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
